# Generated by Django 4.1 on 2022-12-15 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_username', models.CharField(default='jagan', max_length=30)),
                ('fname', models.CharField(default='abc', max_length=50)),
                ('lname', models.CharField(default='abc', max_length=50)),
                ('email', models.CharField(default='abc', max_length=50)),
                ('country', models.CharField(default='abc', max_length=15)),
                ('number', models.IntegerField(default='1234567890')),
                ('pob', models.CharField(default='abc', max_length=50)),
                ('noa', models.CharField(default='abc', max_length=50)),
                ('noc', models.CharField(default='abc', max_length=50)),
                ('sr', models.CharField(default='abc', max_length=50)),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='land.room')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
