# Generated by Django 4.1 on 2022-12-15 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('street', models.CharField(default='abc', max_length=50)),
                ('room_address', models.CharField(max_length=100)),
                ('eircode', models.CharField(default='D02 R590', max_length=20)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='room')),
                ('rent', models.FloatField()),
                ('desc', models.TextField(default='abc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
